name: Code Linting

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
      - releases/**

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Update Rust
        run: rustup update
      - name: Run rustfmt
        uses: wearerequired/lint-action@v2
        with:
            rustfmt: true
      - name: Run clippy
        uses: wearerequired/lint-action@v2
        with:
            clippy: true
            clippy_args: "-FXPLM400"